### ISSUE TITLE
[Suggestion] Only use GPU if it's available

### ISSUE THREAD

**Issue by saattrupdan** [danspeech/punctfix#1]
Hi!

I don't have a GPU, and when I try to initialise the `PunctFixer` as follows I get an `AssertionError`:
```python
>>> from punctfix import PunctFixer
>>> fixer = PunctFixer(language='da')
AssertionError: Torch not compiled with CUDA enabled
```

I realised that the reason for this is quite simple, as `device` is an argument in `PunctFixer`, which defaults to 'cuda'. To prevent others facing the same issue, you could just have a line checking if CUDA is available and set `device` to 'cpu' in that case:
```python
>>> if device == 'cuda' and not torch.cuda.is_available():
>>>     device = 'cpu'
```

**Comment by Rasmusafj** [comment]
Ahh, I see. Great point! :) 

Will fix it asap!
